version: "3.8"
services:
  proxy:
    container_name: "nginx_proxy"
    user: "root"
    image : nginx:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx.conf"
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
  was:
    container_name: "was_tomcat"
    depends_on:
      - proxy
    user: "root"
    image: tomcat:latest
    expose:
      - "80:80"
    volumes:
      - "./tomcat/var/www/html:/usr/local/apache2/htdocs"
