version: "3.8"
services:
  proxy:
    container_name: "nginx_proxy"
    user: "root"
    image : nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx.conf"
  tomcat:
    container_name: "tomcat"
    depends_on:
      - proxy
    user: "root"
    image: tomcat:latest
    expose:
      - "8080"
