version: "3.8"
services:
  proxy:
    container_name: "nginx_proxy"
    user: "root"
    image : nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
  tomcat:
    container_name: "tomcat"
    image: tomcat:latest
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    depends_on:
      - proxy
    user: "root"
    expose:
      - "8080"
  node:
    container_name: "node"
    image: node:latest
    build:
      context: ./node
      dockerfile: Dockerfile
    depends_on:
      - proxy
    volumes:
          - "./node/package.json:/home/node/package.json"
          - "./node/index.js:/home/node/index.js"
          - "./node/node_modules:/home/node/node_modules"
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    tty: true

