version: "3.8"
services:
  proxy:
    container_name: "nginx_proxy"
    user: "root"
    image : nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
#    networks:
#      my_net:
#        - ipv4_address: 172.23.0.2
  tomcat:
    container_name: "tomcat"
    image: tomcat:latest
    build:
      context: ./tomcat
      dockerfile: Dockerfile
    depends_on:
      - proxy
    user: "root"
    expose:
      - "8080"
    restart: always
    tty: true
#    networks:
#      my_net:
#        - ipv4_address: 172.23.0.3
  node:
    container_name: "node"
    image: node:latest
    build:
      context: .
      dockerfile: node/Dockerfile
    depends_on:
      - proxy
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    tty: true
#    networks:
#      my_net:
#        - ipv4_address: 172.23.0.4
  mysql:
    container_name: "mysql"
    image: mysql:latest
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - "./mysql/mysql-volume:/var/lib/mysql"
      - "./mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=psy1234
    expose:
      - "3306"
    tty: true
#    networks:
#      my_net:
#        - ipv4_address: 172.23.0.5
#  network:
#    my_net:
#      driver: bridge
#      enable_ipv6: false
#      ipam:
#        driver: default
#        config:
#          - subnet: 172.23.0.0/24
#          - gateway: 172.23.0.1



